[package]
authors = ["The Rust Project Developers"]
name = "rustc_serialize"
version = "0.0.0"

[lib]
name = "rustc_serialize"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
smallvec = { version = "0.6.5", features = ["union"] }
